language: node_js
sudo: false
node_js:
- node
install:
- npm install
- npm install -g codacy-coverage
script:
- npm run lint
- npm run unit
- npm run build
env:
  matrix:
    secure: WkT5i1LtzMMcI2v7yKCOvS06xqxwRpddLUYSPfSnw+iyhB8bCgdss1NJTeKPSjx4Srbgi0Guqm7G4GmiUqF1/Mqs7CGUl07f9kiXdb+JzJx0SCTBeqlUUd0wYuknyRrXeTT2UnvVRxifS5E9mY+ghNcVbAOEskG5se4qnQg5bnBiTQYOgIwmcritYlBjHY/4fBD7x1FBFkGUL4F6iWHf9GS3FfAeiDTrVPgbUcDThdra/k0EQQgnvsRSCD7p2jRHvAtsWh3yySDCwQ9dGigC/doZpXMtBO/OF+oMdj5DzQ4fv9mkJC2MIn94/2EWJFFqBUyVMkP+KAe6Q3jzyOEF+9UCM/bOl1H9z/jhfu6s23wRouUEgsK93O3ibZqmy0VCzY0K4KaQm6lRwYxjKi54lSxOzdYpyHAkYbR+Fthp2zCv/3AP1F7xKzbLG+RQOOynD7GFeAd1SJCgF09swfh65KF62JcUZlkZR4ljqTWkUomHZWR5kWEnJGLvmhlo+4DmAWZzMG+nhRJfHiONf2tvJ04jxkl9mw/XPwBvEP2Xnj0kUoo0WU865hjjoIces00KlSqcjQG1b2agXNRY3xorrSasj91Cn9YJLm9PqwGovL57tNgJWOqh+OpJYYSzlCXDtkm1LxR+Bsczm50fv4b2SzMrbX0hxyBBNnMZjLbQ11I=
